# Generated by Django 3.2.5 on 2021-08-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210801_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
            ],
            bases=('post.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
